from distutils.core import setup, Extension
import numpy

module = Extension('pyyolo',
	library_dirs=['.'],
	libraries=[
      'yolo',
      'opencv_stitching',
      'opencv_superres',
      'opencv_videostab',
      'opencv_aruco',
      'opencv_bgsegm',
      'opencv_bioinspired',
      'opencv_ccalib',
      'opencv_dnn',
      'opencv_dpm',
      'opencv_fuzzy',
      'opencv_line_descriptor',
      'opencv_optflow',
      'opencv_plot',
      'opencv_reg',
      'opencv_saliency',
      'opencv_stereo',
      'opencv_structured_light',
      'opencv_rgbd',
      'opencv_surface_matching',
      'opencv_tracking',
      'opencv_datasets',
      'opencv_text',
      'opencv_face',
      'opencv_xfeatures2d',
      'opencv_shape',
      'opencv_video',
      'opencv_ximgproc',
      'opencv_calib3d',
      'opencv_features2d',
      'opencv_flann',
      'opencv_xobjdetect',
      'opencv_objdetect',
      'opencv_ml',
      'opencv_xphoto',
      'opencv_highgui',
      'opencv_videoio',
      'opencv_imgcodecs',
      'opencv_photo',
      'opencv_imgproc',
      'opencv_core'
  ],
	include_dirs=[numpy.get_include(), './darknet_cl/include'],
	sources = ['module.c'])

setup (name = 'pyyolo',
	version = '0.1',
	description = 'YOLO wrapper',
	ext_modules = [module])
